version: "3.9"
services:
  activemq:
    image: rmohr/activemq:5.15.9
    ports:
      - "61616:61616" # broker (admin:adminactivemq)(amq:amq)
      - "8161:8161"   # web    http://boot2docker:8161/admin (admin:admin)

  jms-producer:
    image: jms-producer:0.0.1
    depends_on:
      - activemq
    ports:
      - "8081:8081"

  jms-consumer:
    image: jms-consumer:0.0.1
    depends_on:
      - activemq
    ports:
      - "8082:8082"