server:
  port: 8081

spring:
  activemq:
    in-memory: false
  jms:
    template:
      default-destination: sandbox.order.first.queue

app:
  jms:
    custom-destination: sandbox.order.second.queue
